name: Build Python Installer

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - '3.11'
  pull_request:
    branches:
      - 'main'
      - '3.11'

permissions:
  contents: read
  # Retirer artifacts: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}-reusable
  cancel-in-progress: true

jobs:
  build_windows:
    name: 'Build Windows Installer'
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.10'
      - name: Install MSVC Build Tools
        run: |
          choco install visualstudio2019buildtools --version 16.11.4 --params "'/NoRestart /IncludeOptional'"
      - name: Build CPython
        run: |
          .\PCbuild\build.bat -c Release
      - name: Create Installer
        run: |
          .\PCbuild\install.exe /Q /INCLUDE=ALL
      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: python-installer
          path: .\PCbuild\python.exe
