name: TestsMSI

on:
  workflow_dispatch:
  push:
    branches:
    - 'main'
    - '3.11'
    - '3.10'
    - '3.9'
    - '3.8'
    - '3.7'
    paths:
    - 'Tools/msi/**'
  pull_request:
    branches:
    - 'main'
    - '3.11'
    - '3.10'
    - '3.9'
    - '3.8'
    - '3.7'
    paths:
    - 'Tools/msi/**'

permissions:
  contents: read
  actions: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_win32:
    name: 'Windows (x86) Installer'
    runs-on: windows-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - name: Build CPython installer
      run: .\Tools\msi\build.bat -x86
    - name: Upload all Artifacts last
      uses: actions/upload-artifact@v4
      with:
        name: python-all-last
        path: .\PCbuild\PCbuild\*
 
  build_win_amd64:
    name: 'Windows (x64) Installer'
    runs-on: windows-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - name: Build CPython installer
      run: .\Tools\msi\build.bat -x64
    - name: Upload all Artifacts last
      uses: actions/upload-artifact@v4
      with:
        name: python-all-last
        path: .\PCbuild\PCbuild\*
