name: Build Python Installer

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - '3.11'
  pull_request:
    branches:
      - 'main'
      - '3.11'

permissions:
  contents: read
  actions: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_windows:
    name: 'Build Windows Installer'
    runs-on: windows-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      
      - name: Download CPython Source
        run: |
          git clone --branch v3.11.10 https://github.com/python/cpython.git
          cd cpython

      - name: Install Visual Studio Build Tools
        run: |
          Invoke-WebRequest -Uri https://aka.ms/vs/16/release/vs_buildtools.exe -OutFile vs_buildtools.exe
          Start-Process vs_buildtools.exe -ArgumentList "--quiet", "--norestart", "--wait", "--add", "Microsoft.VisualStudio.Workload.VCTools" -NoNewWindow -Wait

      - name: Install WiX Toolset
        run: |
          choco install wixtoolset

      - name: Find Visual Studio installation
        id: vs_installation
        shell: powershell
        run: |
          $vs_install_path = &"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
          echo "VS_INSTALL_PATH=$vs_install_path" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

      - name: Configure environment for Visual Studio
        shell: bash
        run: |
          "$VS_INSTALL_PATH/VC/Auxiliary/Build/vcvarsall.bat" amd64

      - name: Build Python with PGO optimization
        run: |
          cd cpython
          .\PCbuild\build.bat --pgo

      - name: Upload all Artifacts first
        uses: actions/upload-artifact@v4
        with:
          name: python-all-first
          path: .\PCbuild\PCbuild\*

      - name: Build Python MSI installer
        run: |
          cd cpython
          .\PCbuild\build.bat

      - name: Upload all Artifacts last
        uses: actions/upload-artifact@v4
        with:
          name: python-all-last
          path: .\PCbuild\PCbuild\*
