name: Build Python Installer

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - '3.11'
  pull_request:
    branches:
      - 'main'
      - '3.11'

permissions:
  contents: read
  actions: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_windows:
    name: 'Build Windows Installer'
    runs-on: windows-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      
      - name: Download CPython Source
        run: |
          git clone --branch v3.11.10 https://github.com/python/cpython.git
          cd cpython

      - name: Install Visual Studio Build Tools
        run: |
          choco install visualstudio2022buildtools --params "'/Full /IncludeRecommended /IncludeOptional'"
          choco install wixtoolset

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Configure environment for Visual Studio
        shell: bash
        run: |
          "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" amd64

      - name: Build Python with PGO optimization
        run: |
          cd cpython
          ./build.bat --pgo

      - name: Build Python MSI installer
        run: |
          ./build.bat --msi

      - name: Upload MSI Artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-msi
          path: ./PCbuild/amd64/*.msi
