name: Build Python Installer

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - '3.11'
  pull_request:
    branches:
      - 'main'
      - '3.11'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}-reusable
  cancel-in-progress: true

jobs:
  build_windows:
    name: 'Build Windows Installer'
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install MSVC Build Tools
        run: |
          Invoke-WebRequest -Uri https://aka.ms/vs/16/release/vs_buildtools.exe -OutFile vs_buildtools.exe
          Start-Process -Wait -FilePath vs_buildtools.exe -ArgumentList '--quiet --wait --norestart --nocache --install --add Microsoft.VisualStudio.Workload.VCTools'
      - name: Build CPython
        run: |
          cd D:\a\<repository-name>\<repository-name>\  # Remplacez ceci par le bon chemin
          .\PCbuild\build.bat -c Release
      - name: Create Installer
        run: |
          cd D:\a\<repository-name>\<repository-name>\  # Assurez-vous d'être dans le bon répertoire
          .\PCbuild\install.exe /Q /INCLUDE=ALL
      - name: Upload Installer
        uses: actions/upload-artifact@v
