name: Build Python

on:
  push:
    branches:
      - 3.11
  pull_request:
    branches:
      - 3.11

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install required tools
        run: |
          choco install visualstudio2019community --params "--add CMake --add WebDevelopmentBuildTools"
          choco install git
          choco install ninja
          choco install windows-sdk-10

      - name: Build Python
        run: |
          git submodule update --init
          ./configure --with-embed=static --enable-shared
          msbuild /p:Configuration=Release /p:Platform=x64 PCBuild\python.sln

      - name: Build MSI
        run: |
          msbuild /p:Configuration=Release PCBuild\pythonw.sln
          msbuild /p:Configuration=Release PCBuild\msi\python.msi
