name: Build MSI

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - '3.11'
  pull_request:
    branches:
      - 'main'
      - '3.11'

jobs:
  build_win_arm64:
    name: 'Windows (ARM64) Installer'
    runs-on: windows-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Build CPython installer
        run: .\Tools\msi\build.bat -arm64
      - name: Publish MSI artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-arm64-installer
          path: path\to\your\msi\output\*.msi # Change this path to the output directory of the MSI file
