name: Build Python Installer

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - '3.11'
  pull_request:
    branches:
      - 'main'
      - '3.11'

permissions:
  contents: read
  actions: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_windows:
    name: 'Compilation et génération de l installateur Windows'
    runs-on: windows-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v4
      
      - name: Mise en cache des outils de compilation Visual Studio
        uses: actions/cache@v3
        with:
          path: |
            C:\Program Files (x86)\Microsoft Visual Studio
            C:\Program Files\Microsoft Visual Studio
          key: vs-build-tools-${{ runner.os }}-v1
          restore-keys: |
            vs-build-tools-${{ runner.os }}-
      
      - name: Installer Visual Studio Build Tools si non en cache
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          Invoke-WebRequest -Uri https://aka.ms/vs/16/release/vs_buildtools.exe -OutFile vs_buildtools.exe
          Start-Process vs_buildtools.exe -ArgumentList "--quiet", "--norestart", "--wait", "--add", "Microsoft.VisualStudio.Workload.VCTools" -NoNewWindow -Wait

      - name: Télécharger et préparer CPython si non en cache
        uses: actions/cache@v3
        with:
          path: cpython
          key: cpython-${{ runner.os }}-v1
          restore-keys: |
            cpython-${{ runner.os }}-
      
      - name: Cloner le dépôt CPython
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          git clone --branch 3.11 https://github.com/python/cpython.git
          cd cpython

      - name: Compiler CPython (x64)
        run: |
          cd cpython
          .\PCbuild\build.bat -p x64
          
      - name: Générer l'installateur CPython
        run: |
          cd cpython
          & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\msbuild.exe" "PCbuild\pcbuild.proj" /p:Configuration=Release /t:Build /p:Platform=x64 || (Write-Error "Échec de la génération de l'installateur. Vérifiez les journaux pour plus de détails." && exit 1)

      - name: Télécharger les exécutables
        uses: actions/upload-artifact@v4
        with:
          name: executables-python
          path: cpython\PCbuild\amd64\*

      - name: Vérification de l'existence de l'installateur
        run: |
          cd cpython\PCbuild
          if (!(Test-Path install.exe)) {
            Write-Error "install.exe n'a pas été généré. Échec de la compilation."
            exit 1
          }

      - name: Télécharger l'installateur
        uses: actions/upload-artifact@v4
        with:
          name: python-installer
          path: cpython\PCbuild\amd64\install.exe

  build_win_arm64:
    name: 'Compilation et génération de l installateur Windows (ARM64)'
    runs-on: windows-latest
    timeout-minutes: 60
    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v4
      
      - name: Compiler CPython pour ARM64
        run: |
          cd cpython
          .\Tools\msi\build.bat -arm64
          
      - name: Télécharger l'installateur MSI ARM64
        uses: actions/upload-artifact@v4
        with:
          name: python-arm64-installer
          path: cpython\PCbuild\arm64\*.msi  # Chemin ajusté pour ARM64
