name: Build Python Installer

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - '3.11'
  pull_request:
    branches:
      - 'main'
      - '3.11'

permissions:
  contents: read
  actions: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_windows:
    name: 'Build Windows Installer'
    runs-on: windows-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      
      - name: Cache Visual Studio Build Tools
        uses: actions/cache@v3
        with:
          path: vs_buildtools.exe
          key: vs-build-tools-${{ runner.os }}-v1
          restore-keys: |
            vs-build-tools-${{ runner.os }}-

      - name: Install Visual Studio Build Tools
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          Invoke-WebRequest -Uri https://aka.ms/vs/16/release/vs_buildtools.exe -OutFile vs_buildtools.exe
          Start-Process vs_buildtools.exe -ArgumentList "--quiet", "--norestart", "--wait", "--add", "Microsoft.VisualStudio.Workload.VCTools" -NoNewWindow -Wait

      - name: Cache CPython Source
        uses: actions/cache@v3
        with:
          path: cpython
          key: cpython-${{ runner.os }}-v1
          restore-keys: |
            cpython-${{ runner.os }}-

      - name: Download CPython Source
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          git clone --branch 3.11 https://github.com/python/cpython.git
          cd cpython

      - name: Build CPython
        run: |
          cd cpython
          .\PCbuild\build.bat -e -d -p arm64 

      - name: Générer l'installateur CPython
        run: |
          cd cpython
          & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\msbuild.exe" "PCbuild\pcbuild.proj" /p:Configuration=Release /t:Build /p:Platform=x64 || (Write-Error "Installer generation failed. Check the logs for details." && exit 1)

      - name: Upload Executables
        uses: actions/upload-artifact@v4
        with:
          name: python-executables
          path: D:\a\cpython\cpython\cpython\PCbuild\amd64\
      
      - name: List Files in PCbuild Directory
        run: |
          cd cpython\PCbuild
          Get-ChildItem

      - name: Vérifier l'existence de l'installateur
        run: |
          cd cpython\PCbuild
          Get-ChildItem  # Liste tous les fichiers dans le répertoire pour le débogage
          if (!(Test-Path install.exe)) {
            Write-Error "install.exe n'a pas été généré. La compilation a échoué."
            exit 1
          }

      - name: Exécuter l'installateur
        run: |
          cd cpython\PCbuild
          .\install.exe /Q /INCLUDE=ALL
            
      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-installer
          path: .\PCbuild\python.exe

    build_win_arm64:
      name: 'Windows (ARM64) Installer'
      runs-on: windows-latest
      timeout-minutes: 60
      steps:
        - uses: actions/checkout@v4
        - name: Build CPython installer
          run: .\Tools\msi\build.bat -arm64
        - name: Publish MSI artifact
          uses: actions/upload-artifact@v4
          with:
            name: python-arm64-installer
            path: path\to\your\msi\output\*.msi # Change this path to the output directory of the MSI file