name: Build Python Installer

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - '3.11'
  pull_request:
    branches:
      - 'main'
      - '3.11'

permissions:
  contents: read
  actions: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_windows:
    name: 'Build Windows Installer'
    runs-on: windows-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      
      - name: Download CPython Source
        run: |
          git clone --branch v3.11.10 https://github.com/python/cpython.git
          cd cpython

      - name: Install Visual Studio Build Tools
        run: |
          Invoke-WebRequest -Uri https://aka.ms/vs/16/release/vs_buildtools.exe -OutFile vs_buildtools.exe
          Start-Process vs_buildtools.exe -ArgumentList "--quiet", "--norestart", "--wait", "--add", "Microsoft.VisualStudio.Workload.VCTools" -NoNewWindow -Wait

      - name: Build CPython
        run: |
          cd cpython
          .\PCbuild\build.bat -p x64
      - name: Upload Executables
        uses: actions/upload-artifact@v4
        with:
          name: python-executables
          path: D:\a\cpython\cpython\cpython\PCbuild\amd64\
        
          
      - name: Générer l'installateur CPython
        run: |
          cd cpython
          & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\msbuild.exe" "PCbuild\pcbuild.proj" /p:Configuration=Release /t:Build /p:Platform=x64 || (Write-Error "Échec de la génération de l'installateur. Vérifiez les journaux pour plus de détails." && exit 1)

      - name: Télécharger les exécutables
        uses: actions/upload-artifact@v4
        with:
          name: executables-python
          path: D:\a\cpython\cpython\cpython\PCbuild\*

      - name: List Files in PCbuild Directory
        run: |
          cd cpython\PCbuild
          Get-ChildItem
      - name: List Files in amd64 Directory
        run: |
          cd cpython\PCbuild\amd64
          Get-ChildItem

          
      - name: Télécharger l'installateur MSI ARM64
        uses: actions/upload-artifact@v4
        with:
          name: python-arm64-installer
          path: cpython\PCbuild\arm64\*.msi  # Chemin ajusté pour ARM64
